# typed: false
# frozen_string_literal: true

# This file was generated automatically by GitHub Actions
# Do not edit this file manually. It will be overwritten on each release.

class SwiftMockGenerator < Formula
  desc "Generate Swift mocks from annotated source code"
  homepage "https://github.com/manucodin/SwiftMockGenerator"
  url "https://github.com/manucodin/SwiftMockGenerator/archive/refs/tags/v0.5.3.tar.gz"
  sha256 "5d17f4bc933938b0205fbdc8e395e69669f9576e24cf69a12153bda349d80d77"
  license "MIT"

  depends_on macos: :monterey
  depends_on xcode: ["15.0", :build]

  def install
    system "swift", "build", "-c", "release", "--disable-sandbox"
    bin.install ".build/release/swift-mock-generator"
  end

  test do
    system "#{bin}/swift-mock-generator", "--help"
  end
end

