# typed: false
# frozen_string_literal: true

# This file was generated automatically by GitHub Actions
# Do not edit this file manually. It will be overwritten on each release.

class SwiftMockGenerator < Formula
  desc "Generate Swift mocks from annotated source code"
  homepage "https://github.com/manucodin/SwiftMockGenerator"
  url "https://github.com/manucodin/SwiftMockGenerator/archive/refs/tags/v0.5.5.tar.gz"
  sha256 "5f6e72d15637a5b5cf1aa2192ba07d0a9f69e55a6dc08f2d35d0c3fbb0588cdc"
  license "MIT"

  depends_on :macos => :monterey
  depends_on :xcode => ["15.0", :build]

  def install
    system "swift", "build", "-c", "release", "--disable-sandbox"
    bin.install ".build/release/swift-mock-generator"
  end

  test do
    system "#{bin}/swift-mock-generator", "--help"
  end
end

